"use client";

import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@material-tailwind/react";

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create metro app',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const customTheme = {
    drawer: {
      defaultProps: {
        size: 300,
        overlay: true,
        placement: "left",
        overlayProps: undefined,
        className: "",
        dismiss: undefined,
        onClose: undefined,
        transition: {
          type: "tween",
          duration: 0.3,
        },
      },
      styles: {
        base: {
          drawer: {
            position: "fixed",
            zIndex: "z-[9999]",
            pointerEvents: "pointer-events-auto",
            backgroundColor: "bg-white",
            boxSizing: "box-border",
            width: "w-full",
            boxShadow: "shadow-2xl shadow-blue-gray-900/10",
          },
          overlay: {
            position: "absolute",
            inset: "inset-0",
            width: "w-full",
            height: "h-full",
            pointerEvents: "pointer-events-auto",
            zIndex: "z-[9995]",
            backgroundColor: "bg-black",
            backgroundOpacity: "bg-opacity-60",
            backdropBlur: "backdrop-blur-sm",
          },
        },
      },
    },
  };

  return (
      <ThemeProvider value={customTheme}>
        <html lang="en">
          <body className="min-h-screen bg-slate-900">
            {children}
          </body>
        </html>
      </ThemeProvider>
  )
}
